version: '3'

services:
  php:
    build:
      dockerfile: _docker/php/Dockerfile
    volumes:
      - './:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './_docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './_docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306